// Verilog netlist generated by Workcraft 3 (Return of the Hazard), version 3.1.9
module LPG_B_CONTROLLER (ack,reset, LED1, LED2, LED3);
    input ack,reset;
    output LED1, LED2, LED3;

    assign _0_ = LED3 | ~ack | ~LED2;
    assign _1_ = (~LED2 & ack & ~LED3) 							& ~reset;
    assign LED1 = (_0_ & _1_ | LED1 & ((_1_ | _0_)))			& ~reset;
    assign LED2 = (map0 & map1 | LED2 & ((map1 | map0)))		& ~reset;
    assign _4_ = (LED2 & ~ack & ~LED1)								& ~reset;
    assign _5_ = (LED1 | ack | LED2)								& ~reset;
    assign LED3 = (_4_ & _5_ | LED3 & ((_5_ | _4_)))			& ~reset;
    assign map0 = (~ack & LED1)										& ~reset;
    assign map1 = ~LED3 | ~ack;


    // signal values at the initial state:
    // _0_ !_1_ !LED1 !LED2 !_4_ !_5_ !LED3 !map0 map1 !ack
endmodule
