// Verilog netlist generated by Workcraft 3 (Return of the Hazard), version 3.1.9
module UNTITLED (ack_in, req, ack_out, en);
    input ack_in, req;
    output ack_out, en;

    assign ack_out = req & map0 | ack_out & (~~(map0 | req));
    assign en = req & csc0 & csc1;
    assign map0 = csc0 & ~csc1;
    assign csc0 = csc1 & ~ack_out | csc0 & (~~(~ack_out | csc1));
    assign csc1 = ~ack_in & ~csc0 | csc1 & (~~(~csc0 | ~ack_in));


    // signal values at the initial state:
    // !ack_out en !map0 csc0 csc1 !ack_in req
endmodule
